Player.create(name: 'Jadon Sancho', age: 20, team: 'Borussia Dortmund', position: 'Forward', price: 13.79, image:'sancho.jpg' )
Player.create(name: 'Bruno Fernandes', age: 26, team: 'Manchester United', position: 'Midfield', price: 10.53, image:'fernandes.jpg' )
Player.create(name: 'Kylian Mbappe', age: 22, team: 'PSG', position: 'Forward', price: 10.25, image:'mbappe.jpg' )
Player.create(name: 'Trent Alexander-Arnold', age: 22, team: 'Liverpool', position: 'Defender', price: 9.77, image:'arnold.jpg' )
Player.create(name: 'Mason Greenwood', age: 19, team: 'Manchester United', position: 'Forward', price: 9.56, image:'greenwood.jpg' )
Player.create(name: 'Neymar', age: 28, team: 'PSG', position: 'Forward', price: 9.44, image:'neymar.jpg' )
Player.create(name: 'Phil Foden', age: 20, team: 'Manchester City', position: 'Midfield', price: 7.89, image:'foden.png' )
Player.create(name: 'Marcus Rashford', age: 23, team: 'Manchester United', position: 'Forward', price: 7.85, image:'rashford.jpg' )
Player.create(name: 'Erling Braut Haaland', age: 20, team: 'Borussia Dortmund', position: 'Forward', price: 7.74, image:'haaland.jpg' )
Player.create(name: 'Paul Pogba', age: 27, team: 'Manchester United', position: 'Midfield', price: 7.38, image:'pogba.jpg' )

Report.create(player_id: 1, content: 'Great Player, his move to United is priced in so you hope for him to perform from the get go', name: 'United Fan')
Report.create(player_id: 2, content: 'Best performing player in the Premier League since his move, got to have him in your portfolio', name: 'lovetheindex')
Report.create(player_id: 3, content: 'Not really winning any dividends right now, but still so young and so talented', name: 'Indexscout1')
Report.create(player_id: 4, content: 'Takes all the freekicks, and provides all the assists, great if you bought him cheap', name: 'Indexscout1')
Report.create(player_id: 5, content: 'Watched him since he featured in the academy. Very lethal left foot, has already scored hundreds of goals. Future King of the Index!', name: 'Greenwood Gang')
Report.create(player_id: 6, content: 'Former dividend King, needs to move from PSG to be a contender again', name: 'David R')
Report.create(player_id: 7, content: 'Amazing talent, will be a big Dividend earner once he is consistently played', name: 'Michael O')
Report.create(player_id: 8, content: 'Still young, very explosive on his day, but needs to be a lot more consistent', name: 'Roy K')
Report.create(player_id: 9, content: 'Massive Fan, so young but has returned an insane amount of goals considering', name: 'Jurgen K')
Report.create(player_id: 10, content: 'Media darling, not the same since coming back from a major injury, needs to take the game into his own hands. He has the gift!', name: 'OGS')
Report.create(player_id: 1, content: 'Come to United! The number 7 shirt is waiting for you!', name: 'Mark G')
Report.create(player_id: 2, content: 'A revelation since his move. I can definitely see him as the captain of United. Invest heavily!', name: 'Flex')
Report.create(player_id: 2, content: 'Currently living up to his price, the best value player out there', name: 'Warren B')
Report.create(player_id: 5, content: 'Two footed, creates his own goals. Buy now or pay double in a years time!', name: 'Takemyadvice')
Report.create(player_id: 5, content: 'Van Persie, but 100x better. Still under 20 so must be wrapped in cotton wool, but he is the future Index King!', name: 'Hots4Greenwood')
Report.create(player_id: 6, content: 'In his prime, he should get out of PSG to save his reputation. Should be plying his trade in a better league, thats probably why his price isnt rising. Avoid him until he moves', name: 'Robert L')
Report.create(player_id: 8, content: 'Starting to become a Media Buzz performer, and has it in him to win Performance Buzz on his day', name: 'Gary L')
Report.create(player_id: 8, content: 'Agree, slowly taking on more responsibility, which adds more value even when he isnt performing on the pitch', name: '')
Report.create(player_id: 10, content: 'Buy with caution, plenty of Pogba holders out there looking to offload. Not the media draw he once was, and fernandes is stealing all of his performance points', name: 'Paul P')
Report.create(player_id: 10, content: 'Next season will be defining for his future price, needs to put his head down and prove he can take the team to the top', name: 'William I')

Badge.create(player_id: 1, performance_buzz: 4, media_buzz: 10, capital_appreciation: 0, prime_time: 5, twilight_years: 0)
Badge.create(player_id: 2, performance_buzz: 10, media_buzz: 15, capital_appreciation: 5, prime_time: 12, twilight_years: 0)
Badge.create(player_id: 3, performance_buzz: 9, media_buzz: 5, capital_appreciation: 7, prime_time: 8, twilight_years: 0)
Badge.create(player_id: 4, performance_buzz: 16, media_buzz: 6, capital_appreciation: 4, prime_time: 5, twilight_years: 0)
Badge.create(player_id: 5, performance_buzz: 5, media_buzz: 18, capital_appreciation: 9, prime_time: 3, twilight_years: 0)
Badge.create(player_id: 6, performance_buzz: 13, media_buzz: 13, capital_appreciation: 4, prime_time: 17, twilight_years: 0)
Badge.create(player_id: 7, performance_buzz: 5, media_buzz: 9, capital_appreciation: 12, prime_time: 3, twilight_years: 0)
Badge.create(player_id: 8, performance_buzz: 11, media_buzz: 9, capital_appreciation: 7, prime_time: 8, twilight_years: 0)
Badge.create(player_id: 9, performance_buzz: 16, media_buzz: 12, capital_appreciation: 6, prime_time: 3, twilight_years: 0)
Badge.create(player_id: 10, performance_buzz: 7, media_buzz: 18, capital_appreciation: 10, prime_time: 17, twilight_years: 0)
